title: "MeiNa Xie"
email: mx632@nyu.edu
description: >- # this means to ignore newlines until "baseurl:"
  I am new to everything here.
baseurl: "/" 
url: "https://Mina-QwQ.github.io/" 
twitter_username: none
github_username:  Mina-QwQ

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
